version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: snapurl_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-snapurl}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-snapurl_dev}
      POSTGRES_DB: ${DB_NAME:-snapurl}
    ports:
      - "${DB_PORT:-3002}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-snapurl}"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    container_name: snapurl_mail
    restart: unless-stopped
    ports:
      - "${MAILPIT_UI_PORT:-3004}:8025" # UI para ver los correos
      - "${MAILPIT_SMTP_PORT:-3005}:1025" # Puerto SMTP para enviar correos
    environment:
      MP_MAX_MESSAGES: 50
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  postgres_data:
